# Generated by Django 4.0.1 on 2022-02-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=128)),
                ('last', models.CharField(max_length=128)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='directors/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(default=4.0)),
                ('views', models.IntegerField(default=0)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('plot', models.FileField(blank=True, null=True, upload_to='plots/')),
                ('trailer', models.CharField(blank=True, max_length=11, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='imdb.director')),
            ],
        ),
    ]
